/********************************************************************************
** Form generated from reading UI file 'FashionMnistVisualization.ui'
**
** Created by: Qt User Interface Compiler version 5.14.1
**
** WARNING! All changes made in this file will be lost when recompiling UI file!
********************************************************************************/

#ifndef UI_FASHIONMNISTVISUALIZATION_H
#define UI_FASHIONMNISTVISUALIZATION_H

#include <QtCore/QVariant>
#include <QtWidgets/QApplication>
#include <QtWidgets/QLabel>
#include <QtWidgets/QWidget>

QT_BEGIN_NAMESPACE

class Ui_FashionMnistVisualization
{
public:
    QLabel *label;
    QLabel *label_2;

    void setupUi(QWidget *FashionMnistVisualization)
    {
        if (FashionMnistVisualization->objectName().isEmpty())
            FashionMnistVisualization->setObjectName(QString::fromUtf8("FashionMnistVisualization"));
        FashionMnistVisualization->resize(660, 420);
        label = new QLabel(FashionMnistVisualization);
        label->setObjectName(QString::fromUtf8("label"));
        label->setGeometry(QRect(340, 10, 310, 100));
        label->setTextFormat(Qt::AutoText);
        label->setScaledContents(false);
        label->setAlignment(Qt::AlignLeading|Qt::AlignLeft|Qt::AlignTop);
        label->setWordWrap(true);
        label->setOpenExternalLinks(false);
        label_2 = new QLabel(FashionMnistVisualization);
        label_2->setObjectName(QString::fromUtf8("label_2"));
        label_2->setGeometry(QRect(500, 110, 150, 300));

        retranslateUi(FashionMnistVisualization);

        QMetaObject::connectSlotsByName(FashionMnistVisualization);
    } // setupUi

    void retranslateUi(QWidget *FashionMnistVisualization)
    {
        FashionMnistVisualization->setWindowTitle(QCoreApplication::translate("FashionMnistVisualization", "FashionMnistVisualization", nullptr));
        label->setText(QCoreApplication::translate("FashionMnistVisualization", "<html><head/><body><p>Fashion-MNIST is a dataset of Zalando\342\200\231s article images consisting of a training set of 60,000 examples and a test set of 10,000 examples. Each example is a 28\303\22728 grayscale image, associated with a label from 10 classes. Fashion-MNIST is intended to serve as a direct drop-in replacement of the original MNIST dataset for benchmarking machine learning algorithms.</p></body></html>", nullptr));
        label_2->setText(QCoreApplication::translate("FashionMnistVisualization", "<html><head/><body><table border=\"0\" style=\" margin-top:0px; margin-bottom:16px; margin-left:0px; margin-right:0px; border-collapse:collapse;\" cellspacing=\"2\" cellpadding=\"0\" bgcolor=\"#ffffff\"><thead><tr><td bgcolor=\"#ffffff\" style=\" padding-left:13; padding-right:13; padding-top:6; padding-bottom:6; border-top:1px; border-right:1px; border-bottom:1px; border-left:1px; border-top-color:#dfe2e5; border-right-color:#dfe2e5; border-bottom-color:#dfe2e5; border-left-color:#dfe2e5; border-top-style:solid; border-right-style:solid; border-bottom-style:solid; border-left-style:solid;\"><p align=\"center\"><span style=\" font-family:'-apple-system','BlinkMacSystemFont','Segoe UI','Helvetica','Arial','sans-serif','Apple Color Emoji','Segoe UI Emoji'; font-weight:600; color:#24292e; background-color:#ffffff;\">Label</span></p></td><td bgcolor=\"#ffffff\" style=\" padding-left:13; padding-right:13; padding-top:6; padding-bottom:6; border-top:1px; border-right:1px; border-bottom:1px; border-left:1px; border-t"
                        "op-color:#dfe2e5; border-right-color:#dfe2e5; border-bottom-color:#dfe2e5; border-left-color:#dfe2e5; border-top-style:solid; border-right-style:solid; border-bottom-style:solid; border-left-style:solid;\"><p align=\"center\"><span style=\" font-family:'-apple-system','BlinkMacSystemFont','Segoe UI','Helvetica','Arial','sans-serif','Apple Color Emoji','Segoe UI Emoji'; font-weight:600; color:#24292e; background-color:#ffffff;\">Description</span></p></td></tr></thead><tr><td bgcolor=\"#ffffff\" style=\" padding-left:13; padding-right:13; padding-top:6; padding-bottom:6; border-top:1px; border-right:1px; border-bottom:1px; border-left:1px; border-top-color:#dfe2e5; border-right-color:#dfe2e5; border-bottom-color:#dfe2e5; border-left-color:#dfe2e5; border-top-style:solid; border-right-style:solid; border-bottom-style:solid; border-left-style:solid;\"><p><span style=\" font-family:'-apple-system','BlinkMacSystemFont','Segoe UI','Helvetica','Arial','sans-serif','Apple Color Emoji','Segoe UI Emoji'; color:#24292e; "
                        "background-color:#ffffff;\">0</span></p></td><td bgcolor=\"#ffffff\" style=\" padding-left:13; padding-right:13; padding-top:6; padding-bottom:6; border-top:1px; border-right:1px; border-bottom:1px; border-left:1px; border-top-color:#dfe2e5; border-right-color:#dfe2e5; border-bottom-color:#dfe2e5; border-left-color:#dfe2e5; border-top-style:solid; border-right-style:solid; border-bottom-style:solid; border-left-style:solid;\"><p><span style=\" font-family:'-apple-system','BlinkMacSystemFont','Segoe UI','Helvetica','Arial','sans-serif','Apple Color Emoji','Segoe UI Emoji'; color:#24292e; background-color:#ffffff;\">T-shirt/top</span></p></td></tr><tr><td bgcolor=\"#f6f8fa\" style=\" padding-left:13; padding-right:13; padding-top:6; padding-bottom:6; border-top:1px; border-right:1px; border-bottom:1px; border-left:1px; border-top-color:#dfe2e5; border-right-color:#dfe2e5; border-bottom-color:#dfe2e5; border-left-color:#dfe2e5; border-top-style:solid; border-right-style:solid; border-bottom-style:solid; border-le"
                        "ft-style:solid;\"><p><span style=\" font-family:'-apple-system','BlinkMacSystemFont','Segoe UI','Helvetica','Arial','sans-serif','Apple Color Emoji','Segoe UI Emoji'; color:#24292e; background-color:#f6f8fa;\">1</span></p></td><td bgcolor=\"#f6f8fa\" style=\" padding-left:13; padding-right:13; padding-top:6; padding-bottom:6; border-top:1px; border-right:1px; border-bottom:1px; border-left:1px; border-top-color:#dfe2e5; border-right-color:#dfe2e5; border-bottom-color:#dfe2e5; border-left-color:#dfe2e5; border-top-style:solid; border-right-style:solid; border-bottom-style:solid; border-left-style:solid;\"><p><span style=\" font-family:'-apple-system','BlinkMacSystemFont','Segoe UI','Helvetica','Arial','sans-serif','Apple Color Emoji','Segoe UI Emoji'; color:#24292e; background-color:#f6f8fa;\">Trouser</span></p></td></tr><tr><td bgcolor=\"#ffffff\" style=\" padding-left:13; padding-right:13; padding-top:6; padding-bottom:6; border-top:1px; border-right:1px; border-bottom:1px; border-left:1px; border-top-color:#"
                        "dfe2e5; border-right-color:#dfe2e5; border-bottom-color:#dfe2e5; border-left-color:#dfe2e5; border-top-style:solid; border-right-style:solid; border-bottom-style:solid; border-left-style:solid;\"><p><span style=\" font-family:'-apple-system','BlinkMacSystemFont','Segoe UI','Helvetica','Arial','sans-serif','Apple Color Emoji','Segoe UI Emoji'; color:#24292e; background-color:#ffffff;\">2</span></p></td><td bgcolor=\"#ffffff\" style=\" padding-left:13; padding-right:13; padding-top:6; padding-bottom:6; border-top:1px; border-right:1px; border-bottom:1px; border-left:1px; border-top-color:#dfe2e5; border-right-color:#dfe2e5; border-bottom-color:#dfe2e5; border-left-color:#dfe2e5; border-top-style:solid; border-right-style:solid; border-bottom-style:solid; border-left-style:solid;\"><p><span style=\" font-family:'-apple-system','BlinkMacSystemFont','Segoe UI','Helvetica','Arial','sans-serif','Apple Color Emoji','Segoe UI Emoji'; color:#24292e; background-color:#ffffff;\">Pullover</span></p></td></tr><tr><td bgcolo"
                        "r=\"#f6f8fa\" style=\" padding-left:13; padding-right:13; padding-top:6; padding-bottom:6; border-top:1px; border-right:1px; border-bottom:1px; border-left:1px; border-top-color:#dfe2e5; border-right-color:#dfe2e5; border-bottom-color:#dfe2e5; border-left-color:#dfe2e5; border-top-style:solid; border-right-style:solid; border-bottom-style:solid; border-left-style:solid;\"><p><span style=\" font-family:'-apple-system','BlinkMacSystemFont','Segoe UI','Helvetica','Arial','sans-serif','Apple Color Emoji','Segoe UI Emoji'; color:#24292e; background-color:#f6f8fa;\">3</span></p></td><td bgcolor=\"#f6f8fa\" style=\" padding-left:13; padding-right:13; padding-top:6; padding-bottom:6; border-top:1px; border-right:1px; border-bottom:1px; border-left:1px; border-top-color:#dfe2e5; border-right-color:#dfe2e5; border-bottom-color:#dfe2e5; border-left-color:#dfe2e5; border-top-style:solid; border-right-style:solid; border-bottom-style:solid; border-left-style:solid;\"><p><span style=\" font-family:'-apple-system','BlinkMacS"
                        "ystemFont','Segoe UI','Helvetica','Arial','sans-serif','Apple Color Emoji','Segoe UI Emoji'; color:#24292e; background-color:#f6f8fa;\">Dress</span></p></td></tr><tr><td bgcolor=\"#ffffff\" style=\" padding-left:13; padding-right:13; padding-top:6; padding-bottom:6; border-top:1px; border-right:1px; border-bottom:1px; border-left:1px; border-top-color:#dfe2e5; border-right-color:#dfe2e5; border-bottom-color:#dfe2e5; border-left-color:#dfe2e5; border-top-style:solid; border-right-style:solid; border-bottom-style:solid; border-left-style:solid;\"><p><span style=\" font-family:'-apple-system','BlinkMacSystemFont','Segoe UI','Helvetica','Arial','sans-serif','Apple Color Emoji','Segoe UI Emoji'; color:#24292e; background-color:#ffffff;\">4</span></p></td><td bgcolor=\"#ffffff\" style=\" padding-left:13; padding-right:13; padding-top:6; padding-bottom:6; border-top:1px; border-right:1px; border-bottom:1px; border-left:1px; border-top-color:#dfe2e5; border-right-color:#dfe2e5; border-bottom-color:#dfe2e5; border-left"
                        "-color:#dfe2e5; border-top-style:solid; border-right-style:solid; border-bottom-style:solid; border-left-style:solid;\"><p><span style=\" font-family:'-apple-system','BlinkMacSystemFont','Segoe UI','Helvetica','Arial','sans-serif','Apple Color Emoji','Segoe UI Emoji'; color:#24292e; background-color:#ffffff;\">Coat</span></p></td></tr><tr><td bgcolor=\"#f6f8fa\" style=\" padding-left:13; padding-right:13; padding-top:6; padding-bottom:6; border-top:1px; border-right:1px; border-bottom:1px; border-left:1px; border-top-color:#dfe2e5; border-right-color:#dfe2e5; border-bottom-color:#dfe2e5; border-left-color:#dfe2e5; border-top-style:solid; border-right-style:solid; border-bottom-style:solid; border-left-style:solid;\"><p><span style=\" font-family:'-apple-system','BlinkMacSystemFont','Segoe UI','Helvetica','Arial','sans-serif','Apple Color Emoji','Segoe UI Emoji'; color:#24292e; background-color:#f6f8fa;\">5</span></p></td><td bgcolor=\"#f6f8fa\" style=\" padding-left:13; padding-right:13; padding-top:6; padding"
                        "-bottom:6; border-top:1px; border-right:1px; border-bottom:1px; border-left:1px; border-top-color:#dfe2e5; border-right-color:#dfe2e5; border-bottom-color:#dfe2e5; border-left-color:#dfe2e5; border-top-style:solid; border-right-style:solid; border-bottom-style:solid; border-left-style:solid;\"><p><span style=\" font-family:'-apple-system','BlinkMacSystemFont','Segoe UI','Helvetica','Arial','sans-serif','Apple Color Emoji','Segoe UI Emoji'; color:#24292e; background-color:#f6f8fa;\">Sandal</span></p></td></tr><tr><td bgcolor=\"#ffffff\" style=\" padding-left:13; padding-right:13; padding-top:6; padding-bottom:6; border-top:1px; border-right:1px; border-bottom:1px; border-left:1px; border-top-color:#dfe2e5; border-right-color:#dfe2e5; border-bottom-color:#dfe2e5; border-left-color:#dfe2e5; border-top-style:solid; border-right-style:solid; border-bottom-style:solid; border-left-style:solid;\"><p><span style=\" font-family:'-apple-system','BlinkMacSystemFont','Segoe UI','Helvetica','Arial','sans-serif','Apple Colo"
                        "r Emoji','Segoe UI Emoji'; color:#24292e; background-color:#ffffff;\">6</span></p></td><td bgcolor=\"#ffffff\" style=\" padding-left:13; padding-right:13; padding-top:6; padding-bottom:6; border-top:1px; border-right:1px; border-bottom:1px; border-left:1px; border-top-color:#dfe2e5; border-right-color:#dfe2e5; border-bottom-color:#dfe2e5; border-left-color:#dfe2e5; border-top-style:solid; border-right-style:solid; border-bottom-style:solid; border-left-style:solid;\"><p><span style=\" font-family:'-apple-system','BlinkMacSystemFont','Segoe UI','Helvetica','Arial','sans-serif','Apple Color Emoji','Segoe UI Emoji'; color:#24292e; background-color:#ffffff;\">Shirt</span></p></td></tr><tr><td bgcolor=\"#f6f8fa\" style=\" padding-left:13; padding-right:13; padding-top:6; padding-bottom:6; border-top:1px; border-right:1px; border-bottom:1px; border-left:1px; border-top-color:#dfe2e5; border-right-color:#dfe2e5; border-bottom-color:#dfe2e5; border-left-color:#dfe2e5; border-top-style:solid; border-right-style:solid; "
                        "border-bottom-style:solid; border-left-style:solid;\"><p><span style=\" font-family:'-apple-system','BlinkMacSystemFont','Segoe UI','Helvetica','Arial','sans-serif','Apple Color Emoji','Segoe UI Emoji'; color:#24292e; background-color:#f6f8fa;\">7</span></p></td><td bgcolor=\"#f6f8fa\" style=\" padding-left:13; padding-right:13; padding-top:6; padding-bottom:6; border-top:1px; border-right:1px; border-bottom:1px; border-left:1px; border-top-color:#dfe2e5; border-right-color:#dfe2e5; border-bottom-color:#dfe2e5; border-left-color:#dfe2e5; border-top-style:solid; border-right-style:solid; border-bottom-style:solid; border-left-style:solid;\"><p><span style=\" font-family:'-apple-system','BlinkMacSystemFont','Segoe UI','Helvetica','Arial','sans-serif','Apple Color Emoji','Segoe UI Emoji'; color:#24292e; background-color:#f6f8fa;\">Sneaker</span></p></td></tr><tr><td bgcolor=\"#ffffff\" style=\" padding-left:13; padding-right:13; padding-top:6; padding-bottom:6; border-top:1px; border-right:1px; border-bottom:1px;"
                        " border-left:1px; border-top-color:#dfe2e5; border-right-color:#dfe2e5; border-bottom-color:#dfe2e5; border-left-color:#dfe2e5; border-top-style:solid; border-right-style:solid; border-bottom-style:solid; border-left-style:solid;\"><p><span style=\" font-family:'-apple-system','BlinkMacSystemFont','Segoe UI','Helvetica','Arial','sans-serif','Apple Color Emoji','Segoe UI Emoji'; color:#24292e; background-color:#ffffff;\">8</span></p></td><td bgcolor=\"#ffffff\" style=\" padding-left:13; padding-right:13; padding-top:6; padding-bottom:6; border-top:1px; border-right:1px; border-bottom:1px; border-left:1px; border-top-color:#dfe2e5; border-right-color:#dfe2e5; border-bottom-color:#dfe2e5; border-left-color:#dfe2e5; border-top-style:solid; border-right-style:solid; border-bottom-style:solid; border-left-style:solid;\"><p><span style=\" font-family:'-apple-system','BlinkMacSystemFont','Segoe UI','Helvetica','Arial','sans-serif','Apple Color Emoji','Segoe UI Emoji'; color:#24292e; background-color:#ffffff;\">Bag</sp"
                        "an></p></td></tr><tr><td bgcolor=\"#f6f8fa\" style=\" padding-left:13; padding-right:13; padding-top:6; padding-bottom:6; border-top:1px; border-right:1px; border-bottom:1px; border-left:1px; border-top-color:#dfe2e5; border-right-color:#dfe2e5; border-bottom-color:#dfe2e5; border-left-color:#dfe2e5; border-top-style:solid; border-right-style:solid; border-bottom-style:solid; border-left-style:solid;\"><p><span style=\" font-family:'-apple-system','BlinkMacSystemFont','Segoe UI','Helvetica','Arial','sans-serif','Apple Color Emoji','Segoe UI Emoji'; color:#24292e; background-color:#f6f8fa;\">9</span></p></td><td bgcolor=\"#f6f8fa\" style=\" padding-left:13; padding-right:13; padding-top:6; padding-bottom:6; border-top:1px; border-right:1px; border-bottom:1px; border-left:1px; border-top-color:#dfe2e5; border-right-color:#dfe2e5; border-bottom-color:#dfe2e5; border-left-color:#dfe2e5; border-top-style:solid; border-right-style:solid; border-bottom-style:solid; border-left-style:solid;\"><p><span style=\" font-fa"
                        "mily:'-apple-system','BlinkMacSystemFont','Segoe UI','Helvetica','Arial','sans-serif','Apple Color Emoji','Segoe UI Emoji'; color:#24292e; background-color:#f6f8fa;\">Ankle boot</span></p></td></tr></table></body></html>", nullptr));
    } // retranslateUi

};

namespace Ui {
    class FashionMnistVisualization: public Ui_FashionMnistVisualization {};
} // namespace Ui

QT_END_NAMESPACE

#endif // UI_FASHIONMNISTVISUALIZATION_H
